In [2]:
import numpy as np

In [3]:
arr = np.array([1, 2, 3, 4, 5])
print("Array:", arr)

Array: [1 2 3 4 5]


In [4]:
arr.ndim

1

In [5]:
arr.shape

(5,)

In [6]:
len(arr)

5

In [7]:
arr_2d = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

In [8]:
print(arr_2d)

[[1 2 3]
 [4 5 6]]


In [9]:
arr_2d.ndim

2

In [10]:
arr_2d.shape

(2, 3)

In [11]:
len(arr_2d)

2

In [12]:
arr_2d.size

6

In [13]:
type(arr_2d)

numpy.ndarray

In [14]:
arr_2d.dtype

dtype('int32')

In [15]:
np.array([1, 2, 3])

array([1, 2, 3])

In [16]:
np.array([1, 'hello', 2])

array(['1', 'hello', '2'], dtype='<U11')

In [17]:
foo = np.array([1, 'hello', 2])

In [18]:
print(foo)

['1' 'hello' '2']


In [20]:
np.array([
    [1, 2, 3],
    [4.5, 5.6, 6.7]
])

array([[1. , 2. , 3. ],
       [4.5, 5.6, 6.7]])

In [22]:
np.array([
    [1, 2, 3],
    [4, 5,7]
])

array([[1, 2, 3],
       [4, 5, 7]])

In [23]:
np.array(['a', 'b', 'c'])

array(['a', 'b', 'c'], dtype='<U1')

In [25]:
np.array([
    ['a', 'b', 'c'],
    ['d', 'e', 'f'],
    ['g', 'h', 'i']
])

array([['a', 'b', 'c'],
       ['d', 'e', 'f'],
       ['g', 'h', 'i']], dtype='<U1')

In [26]:
np.array([
    [
    ['a', 'b', 'c'],
    ['d', 'e', 'f'],
    ['g', 'h', 'i']
    ],
    [
    ['j', 'k', 'l'],
    ['m', 'n', 'o'],
    ['p', 'q', 'r']
    ]
])

array([[['a', 'b', 'c'],
        ['d', 'e', 'f'],
        ['g', 'h', 'i']],

       [['j', 'k', 'l'],
        ['m', 'n', 'o'],
        ['p', 'q', 'r']]], dtype='<U1')

In [27]:
three_d_array = np.array([
    [
    ['a', 'b', 'c'],
    ['d', 'e', 'f'],
    ['g', 'h', 'i']
    ],
    [
    ['j', 'k', 'l'],
    ['m', 'n', 'o'],
    ['p', 'q', 'r']
    ]
])

In [28]:
np.ndim

<function ndim at 0x000001C564C5B2F0>

In [29]:
three_d_array.ndim

3

In [30]:
np.zeros(shape=3)

array([0., 0., 0.])

In [31]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [32]:
np.zeros(shape=(3, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [33]:
np.full(shape=(2,3), fill_value='ruhi')

array([['ruhi', 'ruhi', 'ruhi'],
       ['ruhi', 'ruhi', 'ruhi']], dtype='<U4')

In [34]:
np.arange(start=0, stop=10, step=2)

array([0, 2, 4, 6, 8])

In [35]:
np.arange(0,10,5)

array([0, 5])

In [36]:
np.arange(20)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [3]:
np.random.randint(low=0, high=10, size=(2, 3))

array([[2, 8, 3],
       [8, 8, 6]])

In [7]:
boo = np.array([1, 2, 3, 4, 5])

In [8]:
print(boo)

[1 2 3 4 5]


In [9]:
boo

array([1, 2, 3, 4, 5])

In [10]:
boo[0]

1

In [11]:
boo[1]

2

In [12]:
boo[1] = 100

In [13]:
boo

array([  1, 100,   3,   4,   5])

In [14]:
boo[4]

5

In [15]:
boo[len(boo)-1]

5

In [16]:
boo[-1]

5

In [17]:
boo[-4]

100

In [20]:
boo[[0,1,0,1]]

array([  1, 100,   1, 100])

In [22]:
np.zeros(shape=3)

array([0., 0., 0.])

In [24]:
boo[np.zeros(shape=3, dtype='int64')]

array([1, 1, 1])

In [25]:
boo[:2]

array([  1, 100])

In [26]:
boo[2:]

array([3, 4, 5])

In [28]:
boo[::2]

array([1, 3, 5])

In [29]:
boo[[0,1,2]] = [10, 20, 30]
print(boo)

[10 20 30  4  5]


In [30]:
boo[[0, 1]] = 20

In [31]:
print(boo)

[20 20 30  4  5]


In [33]:
bar = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

In [34]:
print(bar)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [35]:
bar[1,2]

6

In [36]:
bar[0]

array([1, 2, 3])

In [37]:
bar[0, None]

array([[1, 2, 3]])

In [38]:
bar[:1]

array([[1, 2, 3]])

In [39]:
bar[1:3,[-2,-1]]

array([[5, 6],
       [8, 9]])

In [40]:
bar[0,0] = -1

In [41]:
print(bar)

[[-1  2  3]
 [ 4  5  6]
 [ 7  8  9]]


In [42]:
bar[1] = bar[2]

In [43]:
print(bar)

[[-1  2  3]
 [ 7  8  9]
 [ 7  8  9]]


In [44]:
bar[[0,1,2], [0,1,2]] = [0, 0, 0]
print(bar)

[[0 2 3]
 [7 0 9]
 [7 8 0]]


In [45]:
bar.ndim

2

In [47]:
three_d_array = np.array([
    [
    [1, 2],
    [3, 4],
    [5, 6]
    ],
    [
    [7, 8],
    [9, 10],
    [11, 12]
    ]
])

In [48]:
print(three_d_array)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [49]:
three_d_array[0, : , 1] = 5

In [50]:
print(three_d_array)

[[[ 1  5]
  [ 3  5]
  [ 5  5]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
