### Numpy Array Operations

In [1]:
import numpy as np

In [5]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print("Basic slicing: ", arr[2:7])
print("Slicing with step: ", arr[1:8:2])
print("Slicing with negative step: ", arr[8:1:-2])
print("Negative indexing: ", arr[-3])

Basic slicing:  [3 4 5 6 7]
Slicing with step:  [2 4 6 8]
Slicing with negative step:  [9 7 5 3]
Negative indexing:  8


In [10]:
arr_2d = np.array([[1,2,3],
                   [4,5,6],
                  [7,8,9]])
print("Specific element: ", arr_2d[1, 2])
print("Entire row: ", arr_2d[1])
print("Entire column: ", arr_2d[:, 1])

Specific element:  6
Entire row:  [4 5 6]
Entire column:  [2 5 8]


## Sorting

In [ ]:
unsorted = np.array([3, 1, 4, 1, 5, 9, 2, 6, 5])
print("Sorted array: ", np.sort(unsorted))

arr_2d_unsorted = np.array([[3, 1, 4],
                           [1, 5, 9],
                            [2, 6, 5]])
print("Sorted 2D array by columns: ", np.sort(arr_2d_unsorted, axis=0))
print("Sorted 2D array by rows: ", np.sort(arr_2d_unsorted, axis=1))

Sorted array:  [1 1 2 3 4 5 5 6 9]
Sorted 2D array by columns:  [[1 1 4]
 [2 5 5]
 [3 6 9]]
Sorted 2D array by rows:  [[1 3 4]
 [1 5 9]
 [2 5 6]]


## Filtering

In [ ]:
numbers = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
even_number = numbers[numbers % 2 == 0]

print("Even numbers: ", even_number)


Even numbers:  [ 2  4  6  8 10]


### Filter with mask

In [18]:
mask = numbers > 5
print("Numbers greater than 5: ", numbers[mask])

Numbers greater than 5:  [ 6  7  8  9 10]


## Fancy indexing vs np.where()

In [23]:
indices = [0, 2, 4]
print("Elements at specific indices: ", numbers[indices])

where_result = np.where(numbers > 5)
print(where_result)
print("np.where result: ", numbers[where_result])

Elements at specific indices:  [1 3 5]
(array([5, 6, 7, 8, 9], dtype=int64),)
np.where result:  [ 6  7  8  9 10]


In [30]:
condition_arr = np.where(numbers > 5, numbers * 2, "False")
print("Condition array: ", condition_arr)

Condition array:  ['False' 'False' 'False' 'False' 'False' '12' '14' '16' '18' '20']


### Adding and removing data


In [32]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

combined = np.concatenate((arr1, arr2))
print("Element-wise addition: ", combined)

Element-wise addition:  [1 2 3 4 5 6]
