In [2]:
import numpy as np

In [3]:
arr_1D = np.array([1, 2, 3, 4, 5])

In [4]:
arr_3D = np.array([[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]],
          [[11, 12, 13, 14, 15], [16, 17, 18, 19, 20]]])

In [5]:
arr_1D.ndim

1

In [6]:
arr_3D.ndim

3

In [7]:
arr_1D

array([1, 2, 3, 4, 5])

In [8]:
arr_3D

array([[[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]],

       [[11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20]]])

In [9]:
arr_3D.shape

(2, 2, 5)

In [10]:
py_list = [1,2,3,4,5]
print(py_list * 2)

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]


In [11]:
np_array = np.array([1,2,3,4,5])
print(np_array * 2)

[ 2  4  6  8 10]


In [12]:
import time 
start = time.time()
py_list = [i*2 for i in range(1000000)]
print("\n List operation time: ", time.time()-start)


 List operation time:  0.08500123023986816


In [13]:
start = time.time()
np_array = np.arange(1000000)*2
print("\n Numpy operation time: ", time.time()-start)


 Numpy operation time:  0.006003618240356445


In [14]:
zeros = np.zeros((3, 4))

In [15]:
print("Zeros array: \n", zeros)

Zeros array: 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [16]:
ones = np.ones((2, 3))
print("Ones array: \n", ones)

Ones array: 
 [[1. 1. 1.]
 [1. 1. 1.]]


In [17]:
full = np.full((2,2),7)
print("Full array :\n", full)

Full array :
 [[7 7]
 [7 7]]


In [18]:
random = np.random.random((10,10))

In [19]:
print("Random array :\n", random)

Random array :
 [[6.59769201e-01 5.16199285e-01 8.29041234e-01 7.62017677e-02
  9.04542027e-01 6.09037068e-01 3.67470378e-01 5.22703939e-01
  7.22992258e-01 5.64339678e-01]
 [1.10870048e-01 3.64352094e-01 8.76186182e-01 6.25849056e-01
  4.01791522e-01 1.96269203e-01 1.79494464e-01 6.03632178e-01
  6.68263009e-02 6.46900734e-01]
 [9.69191639e-01 4.74409708e-01 9.51397421e-01 4.09271414e-01
  8.53984659e-01 1.26580407e-01 9.20485083e-01 5.62773968e-01
  4.66029306e-01 5.30211550e-01]
 [8.04513207e-02 4.17923524e-01 2.09860415e-01 2.74199852e-01
  4.58024481e-01 3.06830830e-01 5.39733548e-01 4.47548772e-01
  7.39528612e-01 2.22670148e-01]
 [5.68376136e-01 7.76973011e-01 1.82898048e-01 2.12023505e-01
  7.45021186e-02 1.66411398e-01 7.34497326e-01 6.49310874e-01
  9.95789019e-01 3.07903873e-01]
 [2.79831530e-01 4.11000864e-01 2.87928603e-01 6.38808066e-04
  4.82320559e-01 7.17446123e-01 1.87338916e-01 8.86114413e-01
  5.06558567e-01 6.74000882e-01]
 [7.34384138e-01 3.76105255e-01 1.09590220

In [20]:
sequence = np.arange(0, 30, 3)
print("Sequence array :\n", sequence)

Sequence array :
 [ 0  3  6  9 12 15 18 21 24 27]


In [21]:
# vector 
vector = np.array([1, 2, 3])
print("Vector :\n", vector)

Vector :
 [1 2 3]


In [22]:
# matrix
matrix = np.array([[1,2,3],
                   [4,5,6]])
print("Matrix :\n", matrix)

Matrix :
 [[1 2 3]
 [4 5 6]]


In [23]:
# tensor 
tensor = np.array([[[1, 2, 3],
                    [4, 5, 6]],
                   [[7, 8, 9],
                    [10, 11, 12]]])
print("Tensor :\n", tensor)

Tensor :
 [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [24]:
tensor.ndim

3

In [25]:
arr = np.array([[1, 2, 3], 
                [4, 5, 6]])
print("Shape of array: ", arr.shape)

Shape of array:  (2, 3)


In [26]:
print("Size of array: ", arr.size)

Size of array:  6


In [27]:
arr_3D.size

20

In [28]:
arr.dtype

dtype('int32')

In [29]:
arr = np.arange(12)
print("Original Array :\n", arr)

Original Array :
 [ 0  1  2  3  4  5  6  7  8  9 10 11]


In [30]:
reshape = arr.reshape((3, 4))
print("Reshaped Array :\n", reshape)

Reshaped Array :
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [31]:
reshape.ndim

2

In [32]:
arr.ndim

1

In [33]:
flattened = reshape.flatten()
print("Flattened Array :\n", flattened)

Flattened Array :
 [ 0  1  2  3  4  5  6  7  8  9 10 11]


In [34]:
raveled = reshape.ravel()
print("Raveled Array :\n", raveled)

Raveled Array :
 [ 0  1  2  3  4  5  6  7  8  9 10 11]


In [35]:
# transpose 
transpose = reshape.T
print("Transposed Array :\n", transpose)

Transposed Array :
 [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
