In [3]:
import numpy as np

In [8]:
arr_1D = np.array([1, 2, 3, 4, 5])

In [9]:
arr_3D = np.array([[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]],
          [[11, 12, 13, 14, 15], [16, 17, 18, 19, 20]]])

In [10]:
arr_1D.ndim

1

In [11]:
arr_3D.ndim

3

In [12]:
arr_1D

array([1, 2, 3, 4, 5])

In [13]:
arr_3D

array([[[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]],

       [[11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20]]])

In [14]:
arr_3D.shape

(2, 2, 5)

In [ ]:
py_list = [1,2,3,4,5]
print(py_list * 2)

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]


In [16]:
np_array = np.array([1,2,3,4,5])
print(np_array * 2)

[ 2  4  6  8 10]


In [17]:
import time 
start = time.time()
py_list = [i*2 for i in range(1000000)]
print("\n List operation time: ", time.time()-start)


 List operation time:  0.08300065994262695


In [18]:
start = time.time()
np_array = np.arange(1000000)*2
print("\n Numpy operation time: ", time.time()-start)


 Numpy operation time:  0.005998373031616211


In [19]:
zeros = np.zeros((3, 4))

In [20]:
print("Zeros array: \n", zeros)

Zeros array: 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [21]:
ones = np.ones((2, 3))
print("Ones array: \n", ones)

Ones array: 
 [[1. 1. 1.]
 [1. 1. 1.]]


In [22]:
full = np.full((2,2),7)
print("Full array :\n", full)

Full array :
 [[7 7]
 [7 7]]


In [23]:
random = np.random.random((10,10))

In [24]:
print("Random array :\n", random)

Random array :
 [[0.44849779 0.76271208 0.97122381 0.52618701 0.72768957 0.95998846
  0.67673219 0.61715467 0.27356683 0.78698132]
 [0.75329222 0.52243089 0.56591591 0.02079247 0.19392202 0.47537197
  0.67310048 0.97916321 0.37855356 0.8147513 ]
 [0.19602687 0.76421316 0.47230618 0.76556792 0.08124946 0.14855072
  0.66423701 0.15527383 0.04664863 0.39426955]
 [0.28033961 0.33946618 0.22586958 0.71721561 0.48107861 0.20736655
  0.43807373 0.5956746  0.08603038 0.70972014]
 [0.37158494 0.94152498 0.51812611 0.44244913 0.95123889 0.79374043
  0.8356926  0.8237717  0.06557416 0.39004938]
 [0.18493649 0.41170138 0.55638757 0.11754223 0.26111748 0.03833489
  0.28622904 0.51359581 0.69181686 0.41411638]
 [0.15008153 0.50266451 0.26966107 0.74460794 0.80957016 0.4553196
  0.07700491 0.09011934 0.23748175 0.29316158]
 [0.26923348 0.64259661 0.21366488 0.51304765 0.99502199 0.9803079
  0.49638428 0.14867014 0.23745965 0.78845456]
 [0.24911966 0.1198989  0.34223066 0.36981708 0.344823   0.4691657

In [25]:
sequence = np.arange(0, 30, 3)
print("Sequence array :\n", sequence)

Sequence array :
 [ 0  3  6  9 12 15 18 21 24 27]


In [26]:
# vector 
vector = np.array([1, 2, 3])
print("Vector :\n", vector)

Vector :
 [1 2 3]


In [28]:
# matrix
matrix = np.array([[1,2,3],
                   [4,5,6]])
print("Matrix :\n", matrix)

Matrix :
 [[1 2 3]
 [4 5 6]]


In [ ]:
# tensor 
tensor = np.array([[[1, 2, 3],
                    [4, 5, 6]],
                   [[7, 8, 9],
                    [10, 11, 12]]])
print("Tensor :\n", tensor)

Tensor :
 [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [30]:
tensor.ndim

3

In [31]:
arr = np.array([[1, 2, 3], 
                [4, 5, 6]])
print("Shape of array: ", arr.shape)

Shape of array:  (2, 3)


In [32]:
print("Size of array: ", arr.size)

Size of array:  6


In [33]:
arr_3D.size

20

In [34]:
arr.dtype

dtype('int32')

In [35]:
arr = np.arange(12)
print("Original Array :\n", arr)

Original Array :
 [ 0  1  2  3  4  5  6  7  8  9 10 11]


In [36]:
reshape = arr.reshape((3, 4))
print("Reshaped Array :\n", reshape)

Reshaped Array :
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [37]:
reshape.ndim

2

In [38]:
arr.ndim

1

In [40]:
flattened = reshape.flatten()
print("Flattened Array :\n", flattened)

Flattened Array :
 [ 0  1  2  3  4  5  6  7  8  9 10 11]


In [41]:
raveled = reshape.ravel()
print("Raveled Array :\n", raveled)

Raveled Array :
 [ 0  1  2  3  4  5  6  7  8  9 10 11]


In [42]:
# transpose 
transpose = reshape.T
print("Transposed Array :\n", transpose)

Transposed Array :
 [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
