### Numpy - Numerical Python

### Advantages of Numpy Array:
1. Allows several Mathematical Operations 
2. Faster operations

In [2]:
import numpy as np

List vs Numpy - Time taken 

In [3]:
from time import process_time

Time taken by a list

In [4]:
python_list = [i for i in range(10000)]

start_time = process_time()

python_list = [i+5 for i in python_list]

end_time = process_time()

print(f"Time taken by a list: {end_time - start_time:.10f} seconds")

Time taken by a list: 0.0000000000 seconds


In [5]:
np_array = np.arange(10000)

start_time = process_time()

np_array = np_array + 5

end_time = process_time()

print(f"Time taken by a numpy array: {end_time - start_time:.10f} seconds")

Time taken by a numpy array: 0.0000000000 seconds


Numpy Arrays

In [6]:
# list
list1 = [1, 2, 3, 4, 5]
print("List:", list1)
type(list1)

List: [1, 2, 3, 4, 5]


list

In [7]:
np_array = np.array(list1)
print("Numpy Array:", np_array)
type(np_array)

Numpy Array: [1 2 3 4 5]


numpy.ndarray

In [8]:
# creating a 1D numpy array
a = np.array([1, 2, 3, 4, 5])
print("1D Numpy Array:", a)

1D Numpy Array: [1 2 3 4 5]


In [9]:
a.shape

(5,)

In [10]:
b = np.array([(1, 2, 3), (4, 5, 6)])
print("2D Numpy Array:\n", b)

2D Numpy Array:
 [[1 2 3]
 [4 5 6]]


In [11]:
b.shape

(2, 3)

In [12]:
c = np.array([(1, 2, 3), (4, 5, 6)], dtype=float)
print("2D Numpy Array with float type:\n", c)

2D Numpy Array with float type:
 [[1. 2. 3.]
 [4. 5. 6.]]


Initial placeholders in numpy array

In [13]:
# create a numpy array of Zeros
x = np.zeros((5,5))
x

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [14]:
# create a numpy array of Ones
y = np.ones((5,5))
y

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [15]:
# array of a particular value
z = np.full((5,5),3)
z

array([[3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3]])

In [16]:
# create an identity matrix
identity_matrix = np.eye(5)
identity_matrix

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [17]:
# create a numpy array with random values
random_array = np.random.random((4, 5))
print("Random Numpy Array:\n", random_array)

Random Numpy Array:
 [[0.63002989 0.08122895 0.14387659 0.46686668 0.4879747 ]
 [0.32905064 0.00708009 0.32461248 0.90117812 0.17512912]
 [0.42126748 0.82222457 0.87272138 0.49244861 0.76446764]
 [0.56560455 0.40946785 0.04014792 0.76018642 0.79424435]]


In [18]:
# random integer values array with in a specific range 
random_int_array = np.random.randint(10,100, (4,5))
print("Random Integer Numpy Array:\n", random_int_array)

Random Integer Numpy Array:
 [[45 90 73 72 34]
 [60 60 10 22 42]
 [16 13 17 95 30]
 [33 86 87 95 62]]


In [19]:
# array of evenly spaced values ---> specifying the number of values required
evenly_spaced_array = np.linspace(10, 20, 5)
print("Evenly Spaced Numpy Array:\n", evenly_spaced_array)

Evenly Spaced Numpy Array:
 [10.  12.5 15.  17.5 20. ]


In [20]:
# array of evenly spaced values ---> specifying the step
ed = np.arange(10, 20, 5)
ed

array([10, 15])

In [21]:
# convert a list t oa numpy array
list2 = [1, 2, 3, 4, 5]
np_array_from_list = np.asarray(list2)
print("Numpy Array from List:", np_array_from_list)
type(np_array_from_list)

Numpy Array from List: [1 2 3 4 5]


numpy.ndarray

Analyzing a numpy array

In [22]:
c = np.random.randint(30, 100, (5, 5))
c

array([[30, 67, 33, 82, 69],
       [50, 94, 45, 78, 46],
       [91, 93, 59, 58, 33],
       [41, 63, 44, 62, 55],
       [89, 35, 47, 79, 98]])

In [23]:
# array shape
print("Array Shape:", c.shape)

Array Shape: (5, 5)


In [24]:
# number of dimensions
print("Array Dimensions:", c.ndim)

Array Dimensions: 2


In [25]:
# number of elements in the array
print("Number of Elements in Array:", c.size)

Number of Elements in Array: 25


In [26]:
# checking the data type of the array
print("Data Type of Array:", c.dtype)

Data Type of Array: int32


Mathematical Operations in a numpy array

In [ ]:
list3 = [1, 2, 3, 4, 5]
list4 = [6, 7, 8, 9, 10]

list3+list4 # concatenating or joining two lists

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [29]:
a = np.random.randint(0, 10, (3, 3))
b = np.random.randint(10, 20, (3, 3))

In [31]:
print(a)
print(b)

[[7 5 8]
 [6 6 2]
 [7 0 6]]
[[11 10 14]
 [11 13 18]
 [18 13 12]]


In [ ]:
print(a+b) # element-wise addition

[[18 15 22]
 [17 19 20]
 [25 13 18]]


In [33]:
print(a-b) # element-wise subtraction
print(a*b) # element-wise multiplication
print(a/b) # element-wise division

[[ -4  -5  -6]
 [ -5  -7 -16]
 [-11 -13  -6]]
[[ 77  50 112]
 [ 66  78  36]
 [126   0  72]]
[[0.63636364 0.5        0.57142857]
 [0.54545455 0.46153846 0.11111111]
 [0.38888889 0.         0.5       ]]


In [ ]:
print(np.add(a,b))# element-wise addition using numpy function

[[18 15 22]
 [17 19 20]
 [25 13 18]]


In [ ]:
print(np.subtract(a,b)) # element-wise subtraction using numpy function

[[ -4  -5  -6]
 [ -5  -7 -16]
 [-11 -13  -6]]


In [37]:
print(np.multiply(a,b)) # element-wise multiplication using numpy function
print(np.divide(a,b)) # element-wise division using numpy function

[[ 77  50 112]
 [ 66  78  36]
 [126   0  72]]
[[0.63636364 0.5        0.57142857]
 [0.54545455 0.46153846 0.11111111]
 [0.38888889 0.         0.5       ]]


In [38]:
print(np.sqrt(a)) # element-wise square root
print(np.square(a)) # element-wise square

[[2.64575131 2.23606798 2.82842712]
 [2.44948974 2.44948974 1.41421356]
 [2.64575131 0.         2.44948974]]
[[49 25 64]
 [36 36  4]
 [49  0 36]]


Array Manipulation

In [39]:
arr = np.random.randint(0, 10, (2, 3))
arr.shape # shape of the array
print("Array Shape:", arr.shape)

Array Shape: (2, 3)


In [40]:
arr

array([[6, 6, 9],
       [2, 1, 6]])

In [42]:
# create the transpose
trans = np.transpose(arr)
print(trans)
trans.shape # shape of the transposed array

[[6 2]
 [6 1]
 [9 6]]


(3, 2)

In [43]:
arr = np.random.randint(0, 10, (2, 3))
arr.shape # shape of the array
print("Array Shape:", arr.shape)

Array Shape: (2, 3)


In [44]:
arr

array([[7, 6, 9],
       [4, 7, 0]])

In [45]:
trans2 = arr.T
trans2

array([[7, 4],
       [6, 7],
       [9, 0]])

In [46]:
trans2.shape

(3, 2)

In [47]:
# reshaping array
a = np.random.randint(0, 10, (2, 3))
print(a)
print(a.shape)

[[0 0 3]
 [9 6 7]]
(2, 3)


In [48]:
b = a.reshape(3,2)
print(b)
print(b.shape)

[[0 0]
 [3 9]
 [6 7]]
(3, 2)
