### Numpy - Numerical Python

### Advantages of Numpy Array:
1. Allows several Mathematical Operations 
2. Faster operations

In [1]:
import numpy as np

List vs Numpy - Time taken 

In [2]:
from time import process_time

Time taken by a list

In [3]:
python_list = [i for i in range(10000)]

start_time = process_time()

python_list = [i+5 for i in python_list]

end_time = process_time()

print(f"Time taken by a list: {end_time - start_time:.10f} seconds")

Time taken by a list: 0.0000000000 seconds


In [4]:
np_array = np.arange(10000)

start_time = process_time()

np_array = np_array + 5

end_time = process_time()

print(f"Time taken by a numpy array: {end_time - start_time:.10f} seconds")

Time taken by a numpy array: 0.0000000000 seconds


Numpy Arrays

In [5]:
# list
list1 = [1, 2, 3, 4, 5]
print("List:", list1)
type(list1)

List: [1, 2, 3, 4, 5]


list

In [6]:
np_array = np.array(list1)
print("Numpy Array:", np_array)
type(np_array)

Numpy Array: [1 2 3 4 5]


numpy.ndarray

In [7]:
# creating a 1D numpy array
a = np.array([1, 2, 3, 4, 5])
print("1D Numpy Array:", a)

1D Numpy Array: [1 2 3 4 5]


In [8]:
a.shape

(5,)

In [9]:
b = np.array([(1, 2, 3), (4, 5, 6)])
print("2D Numpy Array:\n", b)

2D Numpy Array:
 [[1 2 3]
 [4 5 6]]


In [10]:
b.shape

(2, 3)

In [11]:
c = np.array([(1, 2, 3), (4, 5, 6)], dtype=float)
print("2D Numpy Array with float type:\n", c)

2D Numpy Array with float type:
 [[1. 2. 3.]
 [4. 5. 6.]]


Initial placeholders in numpy array

In [12]:
# create a numpy array of Zeros
x = np.zeros((5,5))
x

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [13]:
# create a numpy array of Ones
y = np.ones((5,5))
y

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [14]:
# array of a particular value
z = np.full((5,5),3)
z

array([[3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3]])

In [15]:
# create an identity matrix
identity_matrix = np.eye(5)
identity_matrix

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [16]:
# create a numpy array with random values
random_array = np.random.random((4, 5))
print("Random Numpy Array:\n", random_array)

Random Numpy Array:
 [[0.51029992 0.90509347 0.24822344 0.57455318 0.34584477]
 [0.72671008 0.22838674 0.65691689 0.54135307 0.01580754]
 [0.74216871 0.48372037 0.31472737 0.63519704 0.6352534 ]
 [0.61499997 0.10888223 0.24469105 0.38776971 0.41559359]]


In [17]:
# random integer values array with in a specific range 
random_int_array = np.random.randint(10,100, (4,5))
print("Random Integer Numpy Array:\n", random_int_array)

Random Integer Numpy Array:
 [[24 62 99 44 56]
 [82 15 47 27 87]
 [61 48 55 78 50]
 [32 52 59 20 95]]


In [18]:
# array of evenly spaced values ---> specifying the number of values required
evenly_spaced_array = np.linspace(10, 20, 5)
print("Evenly Spaced Numpy Array:\n", evenly_spaced_array)

Evenly Spaced Numpy Array:
 [10.  12.5 15.  17.5 20. ]


In [19]:
# array of evenly spaced values ---> specifying the step
ed = np.arange(10, 20, 5)
ed

array([10, 15])

In [20]:
# convert a list t oa numpy array
list2 = [1, 2, 3, 4, 5]
np_array_from_list = np.asarray(list2)
print("Numpy Array from List:", np_array_from_list)
type(np_array_from_list)

Numpy Array from List: [1 2 3 4 5]


numpy.ndarray

Analyzing a numpy array

In [21]:
c = np.random.randint(30, 100, (5, 5))
c

array([[73, 92, 36, 93, 66],
       [36, 82, 49, 33, 38],
       [99, 45, 85, 79, 93],
       [51, 85, 76, 74, 75],
       [35, 39, 34, 95, 45]], dtype=int32)

In [22]:
# array shape
print("Array Shape:", c.shape)

Array Shape: (5, 5)


In [23]:
# number of dimensions
print("Array Dimensions:", c.ndim)

Array Dimensions: 2


In [24]:
# number of elements in the array
print("Number of Elements in Array:", c.size)

Number of Elements in Array: 25


In [25]:
# checking the data type of the array
print("Data Type of Array:", c.dtype)

Data Type of Array: int32


Mathematical Operations in a numpy array

In [26]:
list3 = [1, 2, 3, 4, 5]
list4 = [6, 7, 8, 9, 10]

list3+list4 # concatenating or joining two lists

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [27]:
a = np.random.randint(0, 10, (3, 3))
b = np.random.randint(10, 20, (3, 3))

In [28]:
print(a)
print(b)

[[7 9 7]
 [9 6 6]
 [4 5 1]]
[[19 11 14]
 [10 19 17]
 [17 16 14]]


In [29]:
print(a+b) # element-wise addition

[[26 20 21]
 [19 25 23]
 [21 21 15]]


In [30]:
print(a-b) # element-wise subtraction
print(a*b) # element-wise multiplication
print(a/b) # element-wise division

[[-12  -2  -7]
 [ -1 -13 -11]
 [-13 -11 -13]]
[[133  99  98]
 [ 90 114 102]
 [ 68  80  14]]
[[0.36842105 0.81818182 0.5       ]
 [0.9        0.31578947 0.35294118]
 [0.23529412 0.3125     0.07142857]]


In [31]:
print(np.add(a,b))# element-wise addition using numpy function

[[26 20 21]
 [19 25 23]
 [21 21 15]]


In [32]:
print(np.subtract(a,b)) # element-wise subtraction using numpy function

[[-12  -2  -7]
 [ -1 -13 -11]
 [-13 -11 -13]]


In [33]:
print(np.multiply(a,b)) # element-wise multiplication using numpy function
print(np.divide(a,b)) # element-wise division using numpy function

[[133  99  98]
 [ 90 114 102]
 [ 68  80  14]]
[[0.36842105 0.81818182 0.5       ]
 [0.9        0.31578947 0.35294118]
 [0.23529412 0.3125     0.07142857]]


In [34]:
print(np.sqrt(a)) # element-wise square root
print(np.square(a)) # element-wise square

[[2.64575131 3.         2.64575131]
 [3.         2.44948974 2.44948974]
 [2.         2.23606798 1.        ]]
[[49 81 49]
 [81 36 36]
 [16 25  1]]


Array Manipulation

In [35]:
arr = np.random.randint(0, 10, (2, 3))
arr.shape # shape of the array
print("Array Shape:", arr.shape)

Array Shape: (2, 3)


In [36]:
arr

array([[6, 9, 6],
       [0, 0, 8]], dtype=int32)

In [37]:
# create the transpose
trans = np.transpose(arr)
print(trans)
trans.shape # shape of the transposed array

[[6 0]
 [9 0]
 [6 8]]


(3, 2)

In [38]:
arr = np.random.randint(0, 10, (2, 3))
arr.shape # shape of the array
print("Array Shape:", arr.shape)

Array Shape: (2, 3)


In [39]:
arr

array([[5, 3, 5],
       [8, 6, 5]], dtype=int32)

In [40]:
trans2 = arr.T
trans2

array([[5, 8],
       [3, 6],
       [5, 5]], dtype=int32)

In [41]:
trans2.shape

(3, 2)

In [42]:
# reshaping array
a = np.random.randint(0, 10, (2, 3))
print(a)
print(a.shape)

[[4 7 7]
 [1 2 5]]
(2, 3)


In [43]:
b = a.reshape(3,2)
print(b)
print(b.shape)

[[4 7]
 [7 1]
 [2 5]]
(3, 2)


In [47]:
bool_arr = b > 4

In [48]:
bool_arr

array([[False,  True],
       [ True, False],
       [False,  True]])

In [49]:
b[bool_arr]

array([7, 7, 5], dtype=int32)

In [50]:
b/b

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [54]:
arr1 = np.arange(0,10)

In [55]:
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [57]:
arr1[0:10]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [58]:
arr1.max()

np.int64(9)

In [59]:
np.sin(arr1)  # element-wise sine function

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [62]:
arr2 = np.arange(10, 20)

In [63]:
np.logaddexp2(arr1, arr2)  # element-wise log addition

array([10.00140819, 11.00140819, 12.00140819, 13.00140819, 14.00140819,
       15.00140819, 16.00140819, 17.00140819, 18.00140819, 19.00140819])

In [ ]:
np.power(arr1, arr2)  # element-wise power 

array([                  0,                   1,                4096,
                   1594323,           268435456,         30517578125,
             2821109907456,     232630513987207,   18014398509481984,
       1350851717672992089])